<?php echo view('operations_approval\Views\partials\styles'); ?>
<style>.receipt-paper{max-width:850px;margin:auto;background:#fff;border-radius:24px;box-shadow:0 25px 60px rgba(7,27,53,.15);overflow:hidden}.receipt-head{position:relative;padding:34px;color:#fff;background:linear-gradient(125deg,#071b35,#124d62)}.receipt-head:after{content:"✓";position:absolute;right:30px;top:25px;display:grid;place-items:center;width:70px;height:70px;border-radius:50%;color:#173000;background:#a8e600;font-size:38px;font-weight:900;box-shadow:0 12px 28px rgba(168,230,0,.3)}.receipt-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:0}.receipt-cell{padding:18px 24px;border-bottom:1px solid #edf2f6}.receipt-label{display:block;margin-bottom:5px;color:#64748b;font-size:11px;font-weight:800;letter-spacing:.7px;text-transform:uppercase}.receipt-value{color:#071b35;font-size:16px;font-weight:700}.receipt-amount{padding:28px;text-align:center;background:#f6fbdc}.receipt-amount strong{display:block;color:#071b35;font-size:36px}.receipt-actions{display:flex;flex-wrap:wrap;gap:10px;padding:24px}.receipt-note{padding:0 24px 28px;color:#64748b;text-align:center}@media(max-width:600px){.receipt-grid{grid-template-columns:1fr}.receipt-head{padding:26px 20px}.receipt-head:after{width:48px;height:48px;right:18px;font-size:26px}.receipt-actions .btn{width:100%}}@media print{.main-scrollable-page,.sidebar-scroll,.receipt-actions,.page-title{display:none!important}.oa-page{padding:0;background:#fff}.receipt-paper{box-shadow:none}}</style>
<div class="oa-page">
<div class="page-title clearfix"><h1><?php echo app_lang('operations_payment_receipt'); ?></h1><div class="title-button-group"><button class="btn btn-default" onclick="window.print()"><i data-feather="printer" class="icon-16"></i> Print</button></div></div>
<article class="receipt-paper">
<header class="receipt-head"><div class="oa-hero-eyebrow">WORKFLOW PAYMENT CONFIRMATION</div><h2>Payment received</h2><p class="mb-0"><?php echo esc($request->request_no); ?></p></header>
<div class="receipt-amount"><span class="receipt-label">Amount paid</span><strong><?php echo esc($receipt['currency']); ?> <?php echo number_format((float)$receipt['amount'],2); ?></strong></div>
<div class="receipt-grid">
<?php foreach(['client_name'=>'Client','payment_date'=>'Payment date','payment_method'=>'Payment method','payment_reference'=>'Payment reference','invoice_number'=>'Invoice number','payment_for'=>'Payment for'] as $key=>$label){ ?><div class="receipt-cell"><span class="receipt-label"><?php echo $label; ?></span><span class="receipt-value"><?php echo esc($receipt[$key]?:'—'); ?></span></div><?php } ?>
</div>
<div class="receipt-actions">
<?php echo form_open(get_uri('operations/receipt/'.$request->id.'/email'),['id'=>'receipt-email-form','class'=>'general-form d-inline']); ?><button class="btn btn-primary"><i data-feather="mail" class="icon-16"></i> <?php echo app_lang('operations_send_email'); ?></button><?php echo form_close(); ?>
<?php echo anchor(get_uri('operations/receipt/'.$request->id.'/share/whatsapp'),'<i data-feather="message-circle" class="icon-16"></i> '.app_lang('operations_send_whatsapp'),['class'=>'btn btn-success','target'=>'_blank']); ?>
<?php echo anchor(get_uri('operations/receipt/'.$request->id.'/share/sms'),'<i data-feather="smartphone" class="icon-16"></i> '.app_lang('operations_send_sms'),['class'=>'btn btn-default']); ?>
<?php echo anchor(get_uri('operations/view/'.$request->id),'<i data-feather="arrow-left" class="icon-16"></i> Back to request',['class'=>'btn btn-default']); ?>
</div><p class="receipt-note">This receipt was generated from an approved WorkFlow request and recorded in its audit history.</p>
</article></div>
<script>$(function(){$('#receipt-email-form').appForm({isModal:false, onSuccess: oaFormFeedback});});</script>
