<div class="float-end m-3"><?php echo anchor(get_uri('operations/export_pdf/' . $request->id), '<i data-feather="download" class="icon-16"></i> ' . app_lang('operations_export_pdf'), ['class' => 'btn btn-default']); ?></div>
<div class="page-title clearfix"><h1><?php echo esc($request->request_no ?: ($request->status === 'draft' ? app_lang('draft') : '—')); ?> — <?php echo esc($request->title); ?></h1></div>
<?php if ($request->status === 'configuration_error') { ?><div class="alert alert-danger"><strong><?php echo app_lang('operations_configuration_error_title'); ?></strong><?php if (!empty($active_stage->name_snapshot)) { ?> (<?php echo esc($active_stage->name_snapshot); ?>)<?php } ?><br><?php echo app_lang('operations_configuration_error_help'); ?><?php if ($can_retry_configuration) { ?>
<div class="mt10"><?php echo form_open(get_uri('operations/retry_configuration/' . $request->id), ['id' => 'operations-retry-configuration-form', 'class' => 'general-form d-inline']); ?><button class="btn btn-danger btn-sm"><i data-feather="refresh-cw" class="icon-14"></i> <?php echo app_lang('operations_retry_configuration'); ?></button><?php echo form_close(); ?></div>
<?php // Re-resolving from the stage's own frozen approver config (the
// button above) only helps when the surrounding DATA has since
// changed - a manager got assigned, a group gained a member. It can
// never help when the config itself is simply wrong (most often a
// "specific people" stage whose only listed person turns out to be
// the requester, filtered out by self-approval rules) - offer a
// direct fallback for that instead of a retry button that would just
// fail the same way again. ?>
<div class="mt10"><a data-bs-toggle="collapse" href="#oa-manual-approver-panel" role="button"><?php echo app_lang('operations_assign_approver_directly'); ?></a><div class="collapse mt10" id="oa-manual-approver-panel"><?php echo form_open(get_uri('operations/retry_configuration/' . $request->id), ['id' => 'operations-manual-retry-form', 'class' => 'general-form']); ?><div class="mb-2"><?php foreach ($staff as $member) { ?><label class="mr-3 d-inline-block"><input type="checkbox" name="manual_approver_ids[]" value="<?php echo (int) $member->id; ?>"> <?php echo esc($member->name); ?></label><?php } ?><?php if (!$staff) { ?><div class="text-muted"><?php echo app_lang('operations_no_staff_found'); ?></div><?php } ?></div><button class="btn btn-outline-danger btn-sm"><?php echo app_lang('operations_assign_and_retry'); ?></button><?php echo form_close(); ?></div></div>
<?php } ?></div><?php } ?>
<div class="row"><div class="col-lg-8"><div class="card"><div class="card-header"><h4><?php echo app_lang('operations_request_details'); ?></h4></div><div class="card-body"><div class="row"><div class="col-md-4"><strong><?php echo app_lang('operations_workflow'); ?></strong><br><?php echo esc($request->workflow_name); ?></div><div class="col-md-4"><strong><?php echo app_lang('requested_by'); ?></strong><br><?php echo esc($request->requester_name ?: '—'); ?></div><div class="col-md-4"><strong><?php echo app_lang('status'); ?></strong><br><span class="badge bg-warning"><?php echo esc(ucwords(str_replace('_', ' ', $request->status))); ?></span></div></div><hr>
<?php foreach ($values as $value) { ?><div class="mb-3"><strong><?php echo esc(ucwords(str_replace('_',' ', $value->field_key))); ?></strong><div>
<?php if (($value->field_type ?? '') === 'richtext') { ?><div class="oa-richtext-value"><?php echo $value->value_text; ?></div>
<?php } elseif (($value->field_type ?? '') === 'spreadsheet') { $grid = json_decode($value->value_text ?: $value->value_json ?: '[]', true) ?: []; ?>
<div class="table-responsive"><table class="table table-bordered table-sm mb-0"><tbody><?php foreach ($grid as $row) { ?><tr><?php foreach ((array) $row as $cell) { ?><td><?php echo esc((string) $cell); ?></td><?php } ?></tr><?php } ?></tbody></table></div>
<?php } else { ?><?php echo nl2br(esc($value->value_text ?: $value->value_json)); ?><?php } ?>
</div></div><?php } ?>
<?php foreach ($customFields as $cf) { ?><div class="mb-3"><strong><?php echo esc($cf->label); ?></strong><div><?php echo nl2br(esc($cf->value)); ?></div></div><?php } ?>
</div></div>
<?php if($request->status==='draft' && (int)$request->requester_id===(int)$login_user->id){ ?><div class="card"><div class="card-body"><?php echo form_open(get_uri('operations/submit/'.$request->id),['id'=>'operations-submit-form','class'=>'general-form']); ?><button class="btn btn-primary"><?php echo app_lang('operations_submit_request'); ?></button><?php echo form_close(); ?></div></div><?php } ?>
<div class="card"><div class="card-header"><h4><?php echo app_lang('operations_approval_timeline'); ?></h4></div><div class="card-body"><div class="vertical-timeline">
<?php foreach ($timeline as $item) { ?><div class="mb-4 border-start ps-3"><strong><?php echo esc($item->name_snapshot); ?></strong> <span class="badge bg-<?php echo $item->status === 'approved' ? 'success' : ($item->status === 'skipped' ? 'secondary' : 'warning'); ?>"><?php echo esc(ucwords($item->status)); ?></span><?php if ($item->actor_name_snapshot) { ?><div><?php echo esc($item->actor_name_snapshot); ?> — <?php echo format_to_datetime($item->decision_at); ?></div><div><?php echo nl2br(esc($item->comment)); ?></div><?php } ?></div><?php } ?>
</div></div></div></div><div class="col-lg-4">
<?php if ($can_decide && $active_stage) { ?><div class="card"><div class="card-header"><h4><?php echo app_lang('operations_your_decision'); ?></h4></div><div class="card-body"><?php if (!empty($is_override_decision)) { ?><div class="alert alert-info mb-3"><?php echo app_lang('operations_override_decision_note'); ?></div><?php } ?><?php echo form_open(get_uri('operations/decide/' . $request->id), ['id' => 'operations-decision-form', 'class' => 'general-form']); ?><input type="hidden" name="stage_instance_id" value="<?php echo (int) $active_stage->id; ?>"><input type="hidden" name="lock_version" value="<?php echo (int) $active_stage->lock_version; ?>"><div class="form-group"><label for="oa-comment"><?php echo app_lang('comment'); ?></label><textarea id="oa-comment" name="comment" class="form-control"></textarea></div><button name="decision" value="approve" class="btn btn-success mr5"><?php echo app_lang('approve'); ?></button><button name="decision" value="return" class="btn btn-warning mr5"><?php echo app_lang('operations_return'); ?></button><button name="decision" value="reject" class="btn btn-danger"><?php echo app_lang('reject'); ?></button><?php echo form_close(); ?><hr><?php echo form_open(get_uri('operations/request_information/'.$request->id),['id'=>'operations-info-form','class'=>'general-form']); ?><textarea name="question" class="form-control mb-2" placeholder="<?php echo app_lang('operations_information_question'); ?>" required></textarea><button class="btn btn-default"><?php echo app_lang('operations_request_information'); ?></button><?php echo form_close(); ?><?php if($active_assignment){ ?><hr><?php echo form_open(get_uri('operations/delegate/'.$request->id),['id'=>'operations-delegate-form','class'=>'general-form']); ?><input type="hidden" name="assignment_id" value="<?php echo $active_assignment->id; ?>"><select name="delegate_id" class="form-control mb-2" required><option value=""><?php echo app_lang('operations_delegate'); ?></option><?php foreach($staff as $member){ ?><option value="<?php echo $member->id; ?>"><?php echo esc($member->name); ?></option><?php } ?></select><input name="reason" class="form-control mb-2" placeholder="<?php echo app_lang('reason'); ?>" required><button class="btn btn-default"><?php echo app_lang('operations_delegate'); ?></button><?php echo form_close(); ?><?php } ?></div></div><?php } ?>
<div class="card"><div class="card-header"><h4><?php echo app_lang('comments'); ?></h4></div><div class="card-body"><?php foreach ($comments as $comment) { ?><div class="mb-3"><strong><?php echo esc($comment->user_name_snapshot); ?></strong><small class="text-muted float-end"><?php echo format_to_datetime($comment->created_at); ?></small><div><?php echo nl2br(esc($comment->comment)); ?></div></div><?php } ?><?php echo form_open(get_uri('operations/comment/' . $request->id), ['id' => 'operations-comment-form', 'class' => 'general-form']); ?><textarea name="comment" class="form-control mb-2" required></textarea><button class="btn btn-primary"><?php echo app_lang('comment'); ?></button><?php echo form_close(); ?></div></div>
<div class="card"><div class="card-header"><h4><?php echo app_lang('attachments'); ?></h4></div><div class="card-body"><?php foreach($attachments as $file){ ?><div class="mb-2"><i data-feather="paperclip" class="icon-14"></i> <?php echo anchor(get_uri('operations/download/'.$file->id),esc($file->original_name)); ?> <small class="text-muted"><?php echo round($file->size_bytes/1024,1); ?> KB</small></div><?php } ?><?php echo form_open(get_uri('operations/upload/'.$request->id),['id'=>'operations-upload-form','class'=>'general-form']); ?><input type="hidden" name="context" value="request"><?php echo view('includes/multi_file_uploader',['hide_description'=>true,'max_files'=>10,'validation_url'=>get_uri('operations/validate_upload')]); ?><button class="btn btn-default"><?php echo app_lang('upload'); ?></button><?php echo form_close(); ?></div></div>
<?php $pdfAttachments=array_values(array_filter($attachments,function($f){return strtolower(pathinfo($f->original_name,PATHINFO_EXTENSION))==='pdf';})); ?>
<?php foreach($conversations as $conversation){ ?><div class="card"><div class="card-header"><h4><?php echo app_lang('operations_information_request'); ?></h4></div><div class="card-body"><strong><?php echo nl2br(esc($conversation->question)); ?></strong><?php if($conversation->response){ ?><hr><?php echo nl2br(esc($conversation->response)); ?><?php }elseif((int)$conversation->assigned_to===(int)$login_user->id){ echo form_open(get_uri('operations/respond_information/'.$request->id),['id'=>'operations-response-form','class'=>'general-form']); ?><input type="hidden" name="conversation_id" value="<?php echo $conversation->id; ?>"><textarea name="response" class="form-control mb-2" required></textarea><button class="btn btn-primary"><?php echo app_lang('operations_send_response'); ?></button><?php echo form_close(); } ?></div></div><?php } ?>
<?php if($request->status==='returned' && (int)$request->requester_id===(int)$login_user->id){ ?><div class="card"><div class="card-header"><h4><?php echo app_lang('operations_correct_and_resubmit'); ?></h4></div><div class="card-body"><?php echo form_open(get_uri('operations/resubmit/'.$request->id),['id'=>'operations-resubmit-form','class'=>'general-form']); ?><?php foreach($values as $value){ ?><label><?php echo esc(ucwords(str_replace('_',' ',$value->field_key))); ?></label><textarea name="field_<?php echo esc($value->field_key); ?>" class="form-control mb-2"><?php echo esc($value->value_text?:$value->value_json); ?></textarea><?php } ?><textarea name="resubmission_comment" class="form-control mb-2" placeholder="<?php echo app_lang('operations_resubmission_comment'); ?>" required></textarea><button class="btn btn-primary"><?php echo app_lang('operations_resubmit'); ?></button><?php echo form_close(); ?></div></div><?php } ?>
<?php if(in_array($request->status,['draft','submitted','pending_approval','returned','information_requested']) && (int)$request->requester_id===(int)$login_user->id){ ?><div class="card"><div class="card-body"><?php echo form_open(get_uri('operations/cancel/'.$request->id),['id'=>'operations-cancel-form','class'=>'general-form']); ?><input name="reason" class="form-control mb-2" placeholder="<?php echo app_lang('operations_cancellation_reason'); ?>" required><button class="btn btn-danger"><?php echo app_lang('cancel'); ?></button><?php echo form_close(); ?></div></div><?php } ?>
<?php if($can_delete){ ?><div class="card"><div class="card-body"><?php echo form_open(get_uri('operations/delete/'.$request->id),['id'=>'operations-delete-form','class'=>'general-form']); ?><button type="submit" class="btn btn-danger w-100" onclick="return confirm('<?php echo esc(app_lang('delete_confirmation_message'), 'js'); ?>');"><i data-feather="trash-2" class="icon-16"></i> <?php echo app_lang('delete'); ?></button><?php echo form_close(); ?></div></div><?php } ?>
</div></div>
<?php if (($request->workflow_code ?? '') === 'CLIENT_PAYMENT_RECEIPT' && in_array($request->status, ['completed','approved'], true)) { ?><div class="card"><div class="card-body"><?php echo anchor(get_uri('operations/receipt/'.$request->id),'<i data-feather="credit-card" class="icon-16"></i> '.app_lang('operations_view_receipt'),['class'=>'btn btn-primary w-100']); ?></div></div><?php } ?>
<?php if ($pdfAttachments) echo view('operations_approval\Views\operations\sign_document', ['pdfAttachments' => $pdfAttachments]); ?>
<?php echo view('operations_approval\Views\partials\styles'); ?><script>$(document).ready(function(){ $('#operations-submit-form,#operations-decision-form,#operations-comment-form,#operations-info-form,#operations-response-form,#operations-resubmit-form,#operations-cancel-form,#operations-delegate-form,#operations-upload-form,#operations-delete-form,#operations-retry-configuration-form,#operations-manual-retry-form').appForm({isModal:false, onSuccess: oaFormFeedback}); });</script>
