<?php echo view('operations_approval\Views\partials\styles'); ?>
<div id="page-content" class="page-wrapper clearfix"><div class="row"><aside class="col-sm-3 col-lg-2"><?php echo view('settings/tabs', ['active_tab' => 'workflow_settings']); ?></aside><main class="col-sm-9 col-lg-10"><div class="oa-page"><div class="page-title clearfix"><h1><?php echo app_lang('workflow_settings'); ?></h1><div class="title-button-group"><?php echo anchor(get_uri('operations_workflows'), '<i data-feather="git-branch" class="icon-16"></i> ' . app_lang('operations_workflow_types'), ['class' => 'btn btn-primary']); ?></div></div>
<div class="row"><div class="col-lg-7"><div class="card"><div class="card-header"><h4><?php echo app_lang('settings'); ?></h4></div><div class="card-body"><?php echo form_open(get_uri('operations_settings/save'),['id'=>'oa-settings-form','class'=>'general-form']); ?>
<div class="alert alert-info d-flex align-items-center justify-content-between"><div><strong><?php echo app_lang('operations_mobile_app'); ?></strong><br><small><?php echo app_lang('operations_mobile_app_help'); ?></small></div><label class="mb-0 ms-3"><input type="checkbox" name="mobile_app_enabled" value="1" <?php echo !empty($settings['mobile_app_enabled'])?'checked':''; ?>> <?php echo app_lang('operations_enabled'); ?></label></div>
<div class="card border mb-3"><div class="card-header"><h4><?php echo app_lang('operations_mobile_modules'); ?></h4><small class="text-muted d-block mt-1"><?php echo app_lang('operations_mobile_modules_help'); ?></small></div><div class="card-body"><div class="row g-3">
<?php foreach(['operations','projects','contracts','proposals','estimates','invoices','payments','tickets'] as $module){ $key='mobile_module_'.$module; ?><div class="col-12 col-xl-6"><label class="d-flex align-items-center justify-content-between gap-3 border rounded p-3 mb-0 w-100" style="min-height:58px"><span class="text-break"><?php echo app_lang('operations_module_'.$module); ?></span><input class="flex-shrink-0" type="checkbox" name="<?php echo $key; ?>" value="1" <?php echo !array_key_exists($key,$settings)||$settings[$key]==='1'?'checked':''; ?>></label></div><?php } ?>
</div></div></div>
<div class="alert alert-warning d-flex align-items-center justify-content-between"><div><strong><?php echo app_lang('operations_customer_signup'); ?></strong><br><small><?php echo app_lang('operations_customer_signup_help'); ?></small></div><label class="mb-0 ms-3"><input type="checkbox" name="customer_signup_enabled" value="1" <?php echo !empty($settings['customer_signup_enabled'])?'checked':''; ?>> <?php echo app_lang('operations_enabled'); ?></label></div>
<div class="alert alert-success d-flex align-items-center justify-content-between"><div><strong><?php echo app_lang('operations_currency_field'); ?></strong><br><small><?php echo app_lang('operations_currency_field_help'); ?></small></div><label class="mb-0 ms-3"><input type="checkbox" name="currency_enabled" value="1" <?php echo !array_key_exists('currency_enabled',$settings)||$settings['currency_enabled']==='1'?'checked':''; ?>> <?php echo app_lang('operations_enabled'); ?></label></div>
<div class="form-group row"><label class="col-md-4" for="oa-allowed-currencies"><?php echo app_lang('operations_allowed_currencies'); ?></label><div class="col-md-8"><input id="oa-allowed-currencies" class="form-control" name="allowed_currencies" value="<?php echo esc($settings['allowed_currencies']??'NGN'); ?>" placeholder="NGN"><small class="text-muted"><?php echo app_lang('operations_allowed_currencies_help'); ?></small></div></div>
<?php foreach(['allowed_extensions','max_file_size_mb','default_page_size','reminder_hours','escalation_hours','retention_days'] as $key){ ?><div class="form-group row"><label class="col-md-4"><?php echo app_lang('operations_'.$key); ?></label><div class="col-md-8"><input class="form-control" name="<?php echo $key; ?>" value="<?php echo esc($settings[$key]??''); ?>"></div></div><?php } ?>
<div class="form-group"><label><input type="checkbox" name="email_enabled" value="1" <?php echo !empty($settings['email_enabled'])?'checked':''; ?>> <?php echo app_lang('operations_email_enabled'); ?></label> <label class="ms-3"><input type="checkbox" name="in_app_enabled" value="1" <?php echo !empty($settings['in_app_enabled'])?'checked':''; ?>> <?php echo app_lang('operations_in_app_enabled'); ?></label></div><button class="btn btn-primary"><?php echo app_lang('save'); ?></button><?php echo form_close(); ?></div></div>
<div class="card"><div class="card-header"><h4><?php echo app_lang('operations_departments'); ?></h4></div><div class="card-body"><?php echo form_open(get_uri('operations_settings/save_department'),['id'=>'oa-department-form','class'=>'general-form']); ?><div class="row"><div class="col"><input name="name" class="form-control" placeholder="<?php echo app_lang('name'); ?>" required></div><div class="col"><input name="code" class="form-control" placeholder="<?php echo app_lang('operations_code'); ?>" required></div><div class="col"><select name="head_user_id" class="form-control select2"><option value=""></option><?php foreach($users as $u){ ?><option value="<?php echo $u->id; ?>"><?php echo esc($u->name); ?></option><?php } ?></select></div><div class="col-auto"><button class="btn btn-primary"><?php echo app_lang('add'); ?></button></div></div><?php echo form_close(); ?><table class="table mt-3"><thead><tr><th><?php echo app_lang('name'); ?></th><th><?php echo app_lang('operations_code'); ?></th></tr></thead><tbody><?php foreach($departments as $d){ ?><tr><td><?php echo esc($d->name); ?></td><td><?php echo esc($d->code); ?></td></tr><?php } ?></tbody></table></div></div></div>
<div class="col-lg-5"><div class="card"><div class="card-header"><h4><?php echo app_lang('operations_delegation'); ?></h4></div><div class="card-body"><?php echo form_open(get_uri('operations_settings/save_delegation'),['id'=>'oa-delegation-form','class'=>'general-form']); ?><select name="user_id" class="form-control select2 mb-2" required><option value=""><?php echo app_lang('operations_original_approver'); ?></option><?php foreach($users as $u){ ?><option value="<?php echo $u->id; ?>"><?php echo esc($u->name); ?></option><?php } ?></select><select name="delegate_id" class="form-control select2 mb-2" required><option value=""><?php echo app_lang('operations_delegate'); ?></option><?php foreach($users as $u){ ?><option value="<?php echo $u->id; ?>"><?php echo esc($u->name); ?></option><?php } ?></select><div class="row"><div class="col"><input name="starts_at" class="form-control" type="datetime-local" required></div><div class="col"><input name="ends_at" class="form-control" type="datetime-local" required></div></div><textarea name="reason" class="form-control mt-2" placeholder="<?php echo app_lang('reason'); ?>" required></textarea><button class="btn btn-primary mt-2"><?php echo app_lang('save'); ?></button><?php echo form_close(); ?><hr><?php foreach($delegations as $d){ ?><div class="mb-2"><strong><?php echo esc($d->first_name.' '.$d->last_name); ?></strong> → <?php echo esc($d->delegate_first_name.' '.$d->delegate_last_name); ?><br><small><?php echo format_to_datetime($d->starts_at).' – '.format_to_datetime($d->ends_at); ?></small></div><?php } ?></div></div></div></div>
</div></main></div></div><script>$(document).ready(function(){$('.select2').select2();$('#oa-settings-form,#oa-department-form,#oa-delegation-form').appForm({isModal:false, onSuccess: oaFormFeedback});});</script>
