<script>$(function(){var $title=$('.page-title').last();if($title.length&&!$title.closest('.oa-page').length){$title.add($title.nextAll()).wrapAll('<div class="oa-page"></div>');}if(window.feather){feather.replace();}});</script>
<script>$(document).on('click','tr[data-href]',function(e){if($(e.target).closest('a,button,input,select,textarea').length)return;window.location=$(this).data('href');});</script>
<script>window.oaFormFeedback=window.oaFormFeedback||function(result){if(result&&result.message){appAlert.success(result.message,{duration:4000});}if(result&&result.redirect_to){setTimeout(function(){window.location=result.redirect_to;},900);}};</script>
<script>
// Delegated (not bound inside request_form.php itself) since that form gets
// reloaded via .load() every time the workflow selector changes - binding
// directly there would stack a fresh duplicate handler on every reload.
(function(){
    function syncSpreadsheet($box){
        var rows=[];
        $box.find('table tbody tr').each(function(){
            var row=[];
            $(this).find('.oa-cell').each(function(){row.push($(this).val());});
            rows.push(row);
        });
        $box.find('.oa-spreadsheet-data').val(JSON.stringify(rows));
    }
    $(document).on('input','.oa-spreadsheet .oa-cell',function(){syncSpreadsheet($(this).closest('.oa-spreadsheet'));});
    $(document).on('click','.oa-add-row',function(){
        var $box=$(this).closest('.oa-spreadsheet');
        var cols=$box.find('table tbody tr:first .oa-cell').length||1;
        var $tr=$('<tr>');
        for(var i=0;i<cols;i++)$tr.append('<td><input type="text" class="form-control form-control-sm oa-cell"></td>');
        $box.find('table tbody').append($tr);
        syncSpreadsheet($box);
    });
    $(document).on('click','.oa-add-column',function(){
        var $box=$(this).closest('.oa-spreadsheet');
        $box.find('table tbody tr').each(function(){$(this).append('<td><input type="text" class="form-control form-control-sm oa-cell"></td>');});
        syncSpreadsheet($box);
    });
})();
</script>
<style>
:root{--oa-navy:#071b35;--oa-lime:#a8e600;--oa-cyan:#2dd4bf;--oa-muted:#64748b;--oa-border:rgba(15,42,76,.09);--oa-shadow:0 18px 45px rgba(7,27,53,.10),0 3px 10px rgba(7,27,53,.05)}
.oa-page{padding:22px;min-height:calc(100vh - 120px);background:radial-gradient(circle at 5% 0,rgba(168,230,0,.10),transparent 24rem),linear-gradient(145deg,#f7fafc,#eef4f8)}.oa-page *{box-sizing:border-box}.oa-page .page-title{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:0 0 22px;border:0;background:transparent}.oa-page .page-title h1{margin:0;color:var(--oa-navy);font-size:clamp(24px,3vw,34px);font-weight:800;letter-spacing:-.8px}.oa-page .page-title h1:after{content:"";display:block;width:52px;height:4px;margin-top:10px;border-radius:10px;background:linear-gradient(90deg,var(--oa-lime),var(--oa-cyan))}
.oa-page .btn{border-radius:12px;padding:10px 16px;font-weight:700;border:0;transition:.2s}.oa-page .btn:hover{transform:translateY(-2px)}.oa-page .btn-primary{color:#102000;background:linear-gradient(135deg,#c4f42b,var(--oa-lime));box-shadow:0 9px 20px rgba(137,190,0,.25),inset 0 1px rgba(255,255,255,.65)}.oa-page .btn-default{color:var(--oa-navy);background:#fff;border:1px solid var(--oa-border);box-shadow:0 7px 18px rgba(7,27,53,.08)}.oa-page .btn-success{background:linear-gradient(135deg,#34d399,#059669)}.oa-page .btn-warning{background:linear-gradient(135deg,#facc15,#f59e0b)}.oa-page .btn-danger{background:linear-gradient(135deg,#fb7185,#e11d48)}
.oa-page .card{overflow:hidden;margin-bottom:22px;border:1px solid rgba(255,255,255,.8);border-radius:20px;background:rgba(255,255,255,.92);box-shadow:var(--oa-shadow);backdrop-filter:blur(12px)}.oa-page .card-header{padding:18px 22px;border-bottom:1px solid var(--oa-border);background:linear-gradient(135deg,rgba(255,255,255,.98),rgba(246,250,252,.88))}.oa-page .card-header h4{margin:0;color:var(--oa-navy);font-size:17px;font-weight:800}.oa-page .card-body{padding:22px}.oa-page .form-control,.oa-page .select2-container .select2-selection{min-height:46px;border:1px solid #dce5ec;border-radius:12px;background:#fbfdff;box-shadow:inset 0 2px 5px rgba(7,27,53,.025)}.oa-page textarea.form-control{min-height:110px}.oa-page .form-control:focus{border-color:#74a900;box-shadow:0 0 0 4px rgba(168,230,0,.14)}.oa-page label{margin-bottom:7px;color:#334155;font-weight:700}
.oa-page .table{margin:0}.oa-page .table thead th{padding:15px 18px;border:0;background:#f4f8fb;color:#607086;font-size:11px;font-weight:800;letter-spacing:.65px;text-transform:uppercase;white-space:nowrap}.oa-page .table tbody td{padding:17px 18px;border-color:#edf2f6;color:#334155;vertical-align:middle}.oa-page .table tbody tr:hover{background:rgba(168,230,0,.055)}.oa-page .table tbody tr[data-href]{cursor:pointer}.oa-page .badge,.oa-status{display:inline-flex;align-items:center;gap:6px;padding:7px 11px;border-radius:30px;font-size:11px;font-weight:800}.oa-status:before{content:"";width:7px;height:7px;border-radius:50%;background:currentColor}.oa-status-success{color:#047857;background:#d1fae5}.oa-status-danger{color:#be123c;background:#ffe4e6}.oa-status-warning{color:#a16207;background:#fef3c7}.oa-status-info{color:#0369a1;background:#e0f2fe}.oa-empty{padding:48px 20px!important;text-align:center;color:var(--oa-muted)!important}.oa-empty i{display:block;margin:0 auto 12px}
.oa-hero{position:relative;overflow:hidden;display:flex;align-items:center;justify-content:space-between;gap:22px;min-height:150px;margin-bottom:22px;padding:28px 30px;border-radius:24px;color:#fff;background:linear-gradient(125deg,var(--oa-navy),#123d66 70%,#16646b);box-shadow:0 22px 50px rgba(7,27,53,.22)}.oa-hero:before,.oa-hero:after{content:"";position:absolute;border-radius:50%}.oa-hero:before{width:170px;height:170px;right:12%;top:-100px;background:rgba(168,230,0,.24);box-shadow:0 0 55px rgba(168,230,0,.2)}.oa-hero:after{width:100px;height:100px;right:3%;bottom:-55px;background:rgba(45,212,191,.2)}.oa-hero-copy,.oa-hero-actions{position:relative;z-index:1}.oa-hero-eyebrow{margin-bottom:8px;color:var(--oa-lime);font-size:11px;font-weight:900;letter-spacing:1.8px}.oa-hero h1{margin:0 0 8px;font-size:clamp(25px,3.4vw,38px);font-weight:800;letter-spacing:-1px}.oa-hero p{max-width:620px;margin:0;color:rgba(255,255,255,.72)}
.oa-kpi-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:16px;margin-bottom:22px}.oa-kpi{position:relative;overflow:hidden;min-height:145px;padding:19px;border:1px solid rgba(255,255,255,.9);border-radius:20px;background:linear-gradient(145deg,#fff,#f4f8fb);box-shadow:var(--oa-shadow);transition:.25s}.oa-kpi:hover{transform:translateY(-6px) rotateX(2deg);box-shadow:0 24px 48px rgba(7,27,53,.15)}.oa-kpi:after{content:"";position:absolute;width:80px;height:80px;right:-36px;bottom:-38px;border-radius:50%;background:var(--kpi-bg,#edf7cf)}.oa-kpi-icon{display:grid;place-items:center;width:43px;height:43px;margin-bottom:14px;border-radius:13px;color:var(--kpi-color,var(--oa-navy));background:var(--kpi-bg,#edf7cf);box-shadow:inset 0 1px rgba(255,255,255,.8),0 8px 16px rgba(7,27,53,.08)}.oa-kpi-value{color:var(--oa-navy);font-size:30px;font-weight:900;line-height:1}.oa-kpi-label{margin-top:8px;color:var(--oa-muted);font-size:12px;font-weight:700;line-height:1.35}.oa-kpi:nth-child(2){--kpi-color:#b45309;--kpi-bg:#fef3c7}.oa-kpi:nth-child(3){--kpi-color:#047857;--kpi-bg:#d1fae5}.oa-kpi:nth-child(4){--kpi-color:#be123c;--kpi-bg:#ffe4e6}.oa-kpi:nth-child(5){--kpi-color:#7c3aed;--kpi-bg:#ede9fe}.oa-kpi:nth-child(6){--kpi-color:#0369a1;--kpi-bg:#e0f2fe}
.oa-section-title{display:flex;align-items:center;justify-content:space-between;gap:14px}.oa-section-icon{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;color:#74a900;background:#effbcf}.oa-option-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.oa-option-grid label{padding:13px;border:1px solid var(--oa-border);border-radius:12px;background:#f8fbfd}.oa-page .vertical-timeline .border-start{position:relative;padding:0 0 24px 28px!important;border-color:#dbe6ec!important}.oa-page .vertical-timeline .border-start:before{content:"";position:absolute;left:-7px;top:2px;width:13px;height:13px;border-radius:50%;background:var(--oa-lime);box-shadow:0 0 0 5px #effbcf}
@media(max-width:1199px){.oa-kpi-grid{grid-template-columns:repeat(3,1fr)}.oa-option-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:767px){.oa-page{padding:14px}.oa-hero{align-items:flex-start;flex-direction:column;padding:24px 20px;border-radius:18px}.oa-hero-actions,.oa-hero-actions .btn{width:100%}.oa-kpi-grid{grid-template-columns:repeat(2,1fr);gap:11px}.oa-kpi{min-height:130px;padding:15px}.oa-page .card{border-radius:16px}.oa-page .card-body{padding:17px}.oa-page .page-title{align-items:flex-start;flex-direction:column}.oa-page .title-button-group,.oa-page .title-button-group .btn{width:100%}.oa-page .table{min-width:720px}.oa-option-grid{grid-template-columns:1fr}.oa-page .row>[class*=col]{margin-bottom:10px}}@media(max-width:390px){.oa-kpi-grid{grid-template-columns:1fr}.oa-kpi{min-height:auto}}
</style>
